// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="multi,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=0,HLS_SYN_LUT=20,HLS_VERSION=2018_3}" *)

module multi (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A,
        B,
        C,
        C_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] A;
input  [31:0] B;
output  [63:0] C;
output   C_ap_vld;

reg C_ap_vld;

wire  signed [31:0] tmp_fu_35_p0;
wire  signed [31:0] tmp_fu_35_p1;
wire   [31:0] tmp_fu_35_p2;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        C_ap_vld = 1'b1;
    end else begin
        C_ap_vld = 1'b0;
    end
end

assign C = $signed(tmp_fu_35_p2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign tmp_fu_35_p0 = B;

assign tmp_fu_35_p1 = A;

assign tmp_fu_35_p2 = ($signed(tmp_fu_35_p0) * $signed(tmp_fu_35_p1));

endmodule //multi
